### ISSUE TITLE
I'd love to update the ui of this project

### ISSUE THREAD

**Issue by DNature** [1click-extensions/1click-webpage-screenshot#189]
I'd love to contribute by creating a nice UI

**Comment by Aminadav** [comment]
Sounds great. Do you a specific suggestions or mockup? What are your skills?

**Comment by DNature** [comment]
Hi @Aminadav. Thanks for the response and i also apologize for the late response.

I've been a lot busy with work lately. I am a user of 1click and i would say you guys have done an amazing job, However, you need a bit of improvement in the UI design. I'd love to be part of this but i'm sure you know how tedious and complicated things can be in the middle of a project.

Best regards :)

**Comment by DNature** [comment]
Hi @Aminadav. Thanks for the response and i also apologize for the late response.

I've been a lot busy with work lately. I am a user of 1click and i would say you guys have done an amazing job, However, i want to point out that i like the recent. I'd love to be part of this but i'm sure you know how tedious and complicated things can be in the middle of a project.

Best regards :)
